fix(#64): use correct host for import file
exasol/exasol-driver-go pull request #66
Opened 2022-05-09 15:14 UTC by Nightapes

Fixes #64

2022-05-09 15:35 UTC, kaklakariada submitted a review, later dismissed

2022-05-09 15:41 UTC, kaklakariada submitted a review, later dismissed

2022-05-09 16:53 UTC, cyrixsimon commented
You shuffle the host list and take always the first host. This could fail depending on the exasol environment - especially in an active/passive cluster environment. 

It is necessary to iterate over the shuffled host list and try to establish a connection. The first successful connection establishment will break the loop. 

Example implementation:
```go
func newProxy(hosts []string, port int) (*proxy, error) {
  var wrappedErr error
  for _, host := range hosts {
	  uri := fmt.Sprintf("%s:%d", host, port)
	  con, err := net.Dial("tcp", uri)
	  if err == nil {
              p := &proxy{
		      connection: con,
		      isClosed:   false,
	      }
      
	      return p, nil
	  } else {
              wrappedErr = fmt.Errorf("%w: could not create TCP connection to %s, %s", ErrInvalidProxyConn, uri, err.Error())
              errorLogger.Print(wrappedErr)
          }
  }
  return nil, wrappedErr
}
```

2022-05-10 06:23 UTC, Nightapes commented
@cyrixsimon Thank you for your comment, we updated the code

2022-05-10 11:13 UTC, kaklakariada approved these changes

2022-05-10 11:21 UTC, kaklakariada requested changes
Please add unit & integration tests

2022-05-10 11:31 UTC, kaklakariada approved these changes

2022-05-10 11:32 UTC, merged